version: "3.8"

services:

  nginx_api:
    container_name: nginx_api
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - backend

  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: api
    expose:
      - 8000
    networks:
      - backend
    env_file:
      - .env_deploy

  elasticsearch:
    image: elasticsearch:7.17.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
    ports:
      - 9200:9200
    networks:
      - backend
    env_file:
      - .env_deploy

  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - 6379:6379
    command:
      - redis-server
    networks:
      - backend
    env_file:
      - .env_deploy

networks:
  backend:
    driver: bridge
