version: "3.8"

services:

  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    container_name: etl
    env_file:
      - etl/.env
    networks:
      - elasticsearch_backend

networks:
  elasticsearch_backend:
    external: true