version: "3.8"

services:

  etl:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: etl
    env_file:
      - app/.env_deploy
    networks:
      - async_api_backend
      - admin_panel_django-network

networks:
  async_api_backend:
    external: true
  admin_panel_django-network:
    external: true